format="$hostname$directory$git_branch$git_status$cmd_duration$fill$localip$time$line_break$character"

[fill]
symbol = " "
style = ""

[hostname]
ssh_only = false
format =  "[ $hostname ](bg:#5A56BC #181926)"
disabled = false

[directory]
format = "[  $path ](bg:#7678ED #181926)"

[git_branch]
format = "[  $branch ](bg:#F7B801 #181926)"

[git_status]
format = '([\[$all_status\]$ahead_behind ](bg:#F7B801 #fe640b))'

[cmd_duration]
format = "[ 󰀠 $duration ](bg:#F4A001 #181926)"

[localip]
ssh_only = false
disabled = false
format = "[ $localipv4 ](bg:#F27103 #181926)"

[time]
disabled = false
format = "[ 󰥔 $time ](bg:#F35B04 #181926)"
